import {
  Icon,
  IconBracketsContain,
  IconBrandGolang,
  IconBrandKotlin,
  IconBrandPowershell,
  IconBrandPython,
  IconBrandRust,
  IconBrandTypescript,
  IconFileCode,
  IconFileCode2,
  IconFileText,
  IconFileTypeCss,
  IconFileTypeCsv,
  IconFileTypeDocx,
  IconFileTypeHtml,
  IconFileTypeJs,
  IconFileTypeJsx,
  IconFileTypePdf,
  IconFileTypePhp,
  IconFileTypePpt,
  IconFileTypeRs,
  IconFileTypeSql,
  IconFileTypeXls,
  IconFileTypeXml,
  IconFileUnknown,
  IconFileZip,
  IconMarkdown,
  IconMusic,
  IconPhoto,
  IconTerminal2,
  IconTex,
  IconVideo,
} from '@tabler/icons-react';

const genericIcons: Record<string, Icon> = {
  video: IconVideo,
  image: IconPhoto,
  audio: IconMusic,
  text: IconFileText,
};

const icons: Record<string, Icon> = {
  // common compressed files
  'application/zip': IconFileZip,
  'application/x-7z-compressed': IconFileZip,
  'application/x-rar-compressed': IconFileZip,
  'application/x-tar': IconFileZip,
  'application/x-bzip2': IconFileZip,
  'application/x-gzip': IconFileZip,

  // common text/document files that are not detected by the 'text' type
  'application/pdf': IconFileTypePdf,
  'application/msword': IconFileTypeDocx,
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document': IconFileTypeDocx,
  'application/vnd.ms-excel': IconFileTypeXls,
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': IconFileTypeXls,
  'application/vnd.ms-powerpoint': IconFileTypePpt,
  'application/vnd.openxmlformats-officedocument.presentationml.presentation': IconFileTypePpt,
  'text/csv': IconFileTypeCsv,

  // other random stuff
  'text/x-sql': IconFileTypeSql,
  'text/css': IconFileTypeCss,
  'text/html': IconFileTypeHtml,
  'text/x-rust': IconFileTypeRs,
  'application/js': IconFileTypeJs,
  'text/javascript': IconFileTypeJs,
  'application/json': IconBracketsContain,
  'text/xml': IconFileTypeXml,
  'application/x-asciicast': IconTerminal2,

  // nodecast text uploads
  'text/x-nodecast-html': IconFileTypeHtml,
  'text/x-nodecast-css': IconFileTypeCss,
  'text/x-nodecast-javascript': IconFileTypeJs,
  'text/x-nodecast-python': IconBrandPython,
  'text/x-nodecast-markdown': IconMarkdown,
  'text/x-nodecast-httpd-php': IconFileTypePhp,
  'text/x-nodecast-sass': IconFileTypeCss,
  'text/x-nodecast-scss': IconFileTypeCss,
  'text/x-nodecast-typescript': IconBrandTypescript,
  'text/x-nodecast-go': IconBrandGolang,
  'text/x-nodecast-rustsrc': IconBrandRust,
  'text/x-nodecast-sh': IconTerminal2,
  'text/x-nodecast-json': IconFileCode2,
  'text/x-nodecast-powershell': IconBrandPowershell,
  'text/x-nodecast-sql': IconFileTypeSql,
  'text/x-nodecast-kotlin': IconBrandKotlin,
  'text/x-nodecast-jsx': IconFileTypeJsx,
  'text/x-nodecast-plain': IconFileText,
  'text/x-nodecast-latex': IconTex,

  'text/x-nodecast-c++src': IconFileCode,
  'text/x-nodecast-ruby': IconFileCode,
  'text/x-nodecast-java': IconFileCode,
  'text/x-nodecast-csrc': IconFileCode,
  'text/x-nodecast-swift': IconFileCode,
  'text/x-nodecast-yaml': IconFileCode,
  'text/x-nodecast-dockerfile': IconFileCode,
  'text/x-zipline-lua': IconFileCode,
  'text/x-zipline-nginx-conf': IconFileCode,
  'text/x-zipline-perl': IconFileCode,
  'text/x-zipline-rsrc': IconFileCode,
  'text/x-zipline-scala': IconFileCode,
  'text/x-zipline-groovy': IconFileCode,
  'text/x-zipline-haskell': IconFileCode,
  'text/x-zipline-elixir': IconFileCode,
  'text/x-zipline-vim': IconFileCode,
  'text/x-zipline-matlab': IconFileCode,
  'text/x-zipline-dart': IconFileCode,
  'text/x-zipline-handlebars-template': IconFileCode,
  'text/x-zipline-hcl': IconFileCode,
  'text/x-zipline-http': IconFileCode,
  'text/x-zipline-ini': IconFileCode,
  'text/x-zipline-coffeescript': IconFileCode,

  // feel free to PR more icons if you want :D
};

export default function fileIcon(type: string): Icon {
  const icon = icons[type] || genericIcons[type.split('/')[0]] || IconFileUnknown;

  return icon;
}
