#!/bin/bash
# NodeCast TrueNAS Scale Installation Script
# Optimized for ZFS with SLOG and Cache drives

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
NODECAST_PATH="/mnt/pool/nodecast"
ZFS_POOL="pool"  # Change this to your ZFS pool name
DOMAIN=""  # Set your domain if you have one

# Functions
print_header() {
    echo -e "${BLUE}"
    echo "=================================================="
    echo "    NodeCast TrueNAS Scale Installation"
    echo "    High-Performance File Server for ZFS"
    echo "=================================================="
    echo -e "${NC}"
}

print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        print_error "This script must be run as root"
        exit 1
    fi
}

check_truenas() {
    if ! command -v midclt &> /dev/null; then
        print_error "This script is designed for TrueNAS Scale"
        exit 1
    fi
    print_status "TrueNAS Scale detected"
}

check_zfs_pool() {
    if ! zfs list "$ZFS_POOL" &> /dev/null; then
        print_error "ZFS pool '$ZFS_POOL' not found. Please update the ZFS_POOL variable in this script."
        exit 1
    fi
    print_status "ZFS pool '$ZFS_POOL' found"
}

create_zfs_datasets() {
    print_status "Creating optimized ZFS datasets..."
    
    # Main nodecast dataset
    if ! zfs list "$ZFS_POOL/nodecast" &> /dev/null; then
        zfs create -o recordsize=1M -o compression=lz4 -o atime=off "$ZFS_POOL/nodecast"
        print_status "Created main nodecast dataset"
    fi
    
    # Database dataset with sync optimization
    if ! zfs list "$ZFS_POOL/nodecast/database" &> /dev/null; then
        zfs create -o recordsize=8K -o compression=lz4 -o sync=always -o logbias=throughput "$ZFS_POOL/nodecast/database"
        print_status "Created database dataset (optimized for SLOG)"
    fi
    
    # Upload dataset with large recordsize
    if ! zfs list "$ZFS_POOL/nodecast/uploads" &> /dev/null; then
        zfs create -o recordsize=1M -o compression=lz4 -o sync=standard "$ZFS_POOL/nodecast/uploads"
        print_status "Created uploads dataset"
    fi
    
    # Temp dataset on fast storage
    if ! zfs list "$ZFS_POOL/nodecast/temp" &> /dev/null; then
        zfs create -o recordsize=128K -o compression=lz4 -o sync=disabled "$ZFS_POOL/nodecast/temp"
        print_status "Created temp dataset"
    fi
    
    # Public assets dataset
    if ! zfs list "$ZFS_POOL/nodecast/public" &> /dev/null; then
        zfs create -o recordsize=128K -o compression=lz4 -o primarycache=all "$ZFS_POOL/nodecast/public"
        print_status "Created public dataset"
    fi
    
    # Themes dataset
    if ! zfs list "$ZFS_POOL/nodecast/themes" &> /dev/null; then
        zfs create -o recordsize=64K -o compression=lz4 "$ZFS_POOL/nodecast/themes"
        print_status "Created themes dataset"
    fi
}

set_permissions() {
    print_status "Setting proper permissions..."
    mkdir -p "$NODECAST_PATH"/{database,uploads,temp,public,themes}
    
    # Create nodecast user if it doesn't exist
    if ! id "nodecast" &>/dev/null; then
        useradd -r -u 1001 -g users -s /sbin/nologin nodecast
        print_status "Created nodecast user"
    fi
    
    chown -R nodecast:users "$NODECAST_PATH"
    chmod -R 755 "$NODECAST_PATH"
}

download_compose_files() {
    print_status "Downloading NodeCast compose files..."
    
    cd "$NODECAST_PATH"
    
    # Download docker-compose.truenas.yml
    if ! wget -O docker-compose.yml "https://raw.githubusercontent.com/InfamousMorningstar/NodeCase/trunk/docker-compose.truenas.yml" 2>/dev/null; then
        print_warning "Could not download compose file from GitHub, using local template"
        create_compose_template
    fi
    
    # Download environment template
    if ! wget -O .env.example "https://raw.githubusercontent.com/InfamousMorningstar/NodeCase/trunk/.env.truenas" 2>/dev/null; then
        print_warning "Could not download .env template from GitHub, using local template"
        create_env_template
    fi
}

create_compose_template() {
    print_status "Creating docker-compose.yml template..."
    
    cat > "$NODECAST_PATH/docker-compose.yml" << 'EOF'
# Generated by NodeCast installer
version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: nodecast-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=nodecast
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=nodecast
    volumes:
      - /mnt/pool/nodecast/database:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'nodecast']
      interval: 10s
      timeout: 5s
      retries: 5

  nodecast:
    image: ghcr.io/infamousmorningstar/nodecast:latest
    container_name: nodecast-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://nodecast:${POSTGRES_PASSWORD}@postgres:5432/nodecast
      - CORE_HOSTNAME=0.0.0.0
      - CORE_SECRET=${CORE_SECRET}
      - DATASOURCE_TYPE=local
      - DATASOURCE_LOCAL_DIRECTORY=/nodecast/uploads
    volumes:
      - /mnt/pool/nodecast/uploads:/nodecast/uploads
      - /mnt/pool/nodecast/temp:/nodecast/temp
      - /mnt/pool/nodecast/public:/nodecast/public
      - /mnt/pool/nodecast/themes:/nodecast/themes
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
EOF
}

create_env_template() {
    print_status "Creating .env template..."
    
    cat > "$NODECAST_PATH/.env.example" << 'EOF'
# NodeCast Configuration
POSTGRES_PASSWORD=change_this_secure_password
CORE_SECRET=change_this_to_a_32_character_or_longer_secret
NODECAST_PORT=3000
WEBSITE_TITLE=NodeCast - High-Performance File Server
FEATURES_USER_REGISTRATION=false
EOF
}

generate_secrets() {
    print_status "Generating secure configuration..."
    
    if [[ ! -f "$NODECAST_PATH/.env" ]]; then
        cp "$NODECAST_PATH/.env.example" "$NODECAST_PATH/.env"
        
        # Generate random passwords
        POSTGRES_PASS=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-25)
        CORE_SECRET=$(openssl rand -base64 48 | tr -d "=+/" | cut -c1-32)
        
        # Update .env file
        sed -i "s/change_this_secure_password/$POSTGRES_PASS/g" "$NODECAST_PATH/.env"
        sed -i "s/change_this_to_a_32_character_or_longer_secret/$CORE_SECRET/g" "$NODECAST_PATH/.env"
        
        print_status "Generated secure passwords in .env file"
    else
        print_warning ".env file already exists, skipping generation"
    fi
}

check_slog() {
    print_status "Checking ZFS SLOG configuration..."
    if zpool status "$ZFS_POOL" | grep -q "logs"; then
        print_status "SLOG device found - optimal for database performance"
    else
        print_warning "No SLOG device detected. Consider adding one for optimal database performance:"
        print_warning "  zpool add $ZFS_POOL log /dev/disk/by-id/your-slog-device"
    fi
}

check_l2arc() {
    print_status "Checking ZFS L2ARC configuration..."
    if zpool status "$ZFS_POOL" | grep -q "cache"; then
        print_status "L2ARC cache device found - optimal for read performance"
    else
        print_warning "No L2ARC cache device detected. Consider adding one for better read performance:"
        print_warning "  zpool add $ZFS_POOL cache /dev/disk/by-id/your-cache-device"
    fi
}

start_services() {
    print_status "Starting NodeCast services..."
    
    cd "$NODECAST_PATH"
    
    if command -v docker-compose &> /dev/null; then
        docker-compose pull
        docker-compose up -d
    elif command -v docker &> /dev/null && docker compose version &> /dev/null; then
        docker compose pull
        docker compose up -d
    else
        print_error "Docker Compose not found. Please install Docker and Docker Compose."
        return 1
    fi
    
    print_status "NodeCast services started"
}

show_final_instructions() {
    echo -e "${GREEN}"
    echo "=================================================="
    echo "    NodeCast Installation Complete!"
    echo "=================================================="
    echo -e "${NC}"
    
    echo "📁 Installation Path: $NODECAST_PATH"
    echo "🌐 Web Interface: http://$(hostname -I | awk '{print $1}'):3000"
    echo "📊 Database: PostgreSQL (optimized for ZFS with SLOG)"
    echo ""
    echo "🔧 Configuration:"
    echo "   - Edit $NODECAST_PATH/.env to customize settings"
    echo "   - View logs: cd $NODECAST_PATH && docker-compose logs -f"
    echo "   - Restart: cd $NODECAST_PATH && docker-compose restart"
    echo ""
    echo "📈 ZFS Monitoring Commands:"
    echo "   - Pool status: zpool status $ZFS_POOL"
    echo "   - Dataset usage: zfs list | grep nodecast"
    echo "   - ARC stats: arc_summary"
    echo ""
    echo "🚀 Performance Tips:"
    echo "   - Monitor SLOG utilization: zpool iostat -v 5"
    echo "   - Check L2ARC hit rate: arc_summary | grep L2"
    echo "   - Enable ZFS scrub: zpool scrub $ZFS_POOL"
    echo ""
    print_status "NodeCast is ready for high-performance file sharing!"
}

# Main installation flow
main() {
    print_header
    
    print_status "Starting NodeCast installation for TrueNAS Scale..."
    
    check_root
    check_truenas
    check_zfs_pool
    create_zfs_datasets
    set_permissions
    download_compose_files
    generate_secrets
    check_slog
    check_l2arc
    start_services
    
    show_final_instructions
}

# Run main function
main "$@"