blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/your-username/nodecast/discussions/new?category=ideas&title=Your%20brief%20description%20here&labels=feature
    about: Ask for a new feature
  - name: Documentation
    url: https://nodecast.docs
    about: Maybe take a look a the docs?
  - name: NodeCast Community
    url: https://discord.gg/nodecast
    about: Ask for help with anything related to NodeCast!
