/*
  Warnings:

  - You are about to drop the `Zipline` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE "public"."Zipline";

-- CreateTable
CREATE TABLE "public"."NodeCast" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "firstSetup" BOOLEAN NOT NULL DEFAULT true,
    "coreReturnHttpsUrls" BOOLEAN NOT NULL DEFAULT false,
    "coreDefaultDomain" TEXT,
    "coreTempDirectory" TEXT NOT NULL,
    "chunksEnabled" BOOLEAN NOT NULL DEFAULT true,
    "chunksMax" TEXT NOT NULL DEFAULT '95mb',
    "chunksSize" TEXT NOT NULL DEFAULT '25mb',
    "tasksDeleteInterval" TEXT NOT NULL DEFAULT '30m',
    "tasksClearInvitesInterval" TEXT NOT NULL DEFAULT '30m',
    "tasksMaxViewsInterval" TEXT NOT NULL DEFAULT '30m',
    "tasksThumbnailsInterval" TEXT NOT NULL DEFAULT '30m',
    "tasksMetricsInterval" TEXT NOT NULL DEFAULT '30m',
    "filesRoute" TEXT NOT NULL DEFAULT '/u',
    "filesLength" INTEGER NOT NULL DEFAULT 6,
    "filesDefaultFormat" TEXT NOT NULL DEFAULT 'random',
    "filesDisabledExtensions" TEXT[],
    "filesMaxFileSize" TEXT NOT NULL DEFAULT '100mb',
    "filesDefaultExpiration" TEXT,
    "filesAssumeMimetypes" BOOLEAN NOT NULL DEFAULT false,
    "filesDefaultDateFormat" TEXT NOT NULL DEFAULT 'YYYY-MM-DD_HH:mm:ss',
    "filesRemoveGpsMetadata" BOOLEAN NOT NULL DEFAULT false,
    "filesRandomWordsNumAdjectives" INTEGER NOT NULL DEFAULT 2,
    "filesRandomWordsSeparator" TEXT NOT NULL DEFAULT '-',
    "filesDefaultCompressionFormat" TEXT DEFAULT 'jpg',
    "urlsRoute" TEXT NOT NULL DEFAULT '/go',
    "urlsLength" INTEGER NOT NULL DEFAULT 6,
    "featuresImageCompression" BOOLEAN NOT NULL DEFAULT true,
    "featuresRobotsTxt" BOOLEAN NOT NULL DEFAULT true,
    "featuresHealthcheck" BOOLEAN NOT NULL DEFAULT true,
    "featuresUserRegistration" BOOLEAN NOT NULL DEFAULT false,
    "featuresOauthRegistration" BOOLEAN NOT NULL DEFAULT false,
    "featuresDeleteOnMaxViews" BOOLEAN NOT NULL DEFAULT true,
    "featuresThumbnailsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "featuresThumbnailsNumberThreads" INTEGER NOT NULL DEFAULT 4,
    "featuresThumbnailsFormat" TEXT NOT NULL DEFAULT 'jpg',
    "featuresMetricsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "featuresMetricsAdminOnly" BOOLEAN NOT NULL DEFAULT false,
    "featuresMetricsShowUserSpecific" BOOLEAN NOT NULL DEFAULT true,
    "featuresVersionChecking" BOOLEAN NOT NULL DEFAULT true,
    "featuresVersionAPI" TEXT NOT NULL DEFAULT 'https://nodecast-version.api.com',
    "invitesEnabled" BOOLEAN NOT NULL DEFAULT true,
    "invitesLength" INTEGER NOT NULL DEFAULT 6,
    "websiteTitle" TEXT NOT NULL DEFAULT 'NodeCast',
    "websiteTitleLogo" TEXT,
    "websiteExternalLinks" JSONB NOT NULL DEFAULT '[{ "name": "GitHub", "url": "https://github.com/InfamousMorningstar/nodecast"}, { "name": "Documentation", "url": "https://nodecast.docs/"}]',
    "websiteLoginBackground" TEXT,
    "websiteLoginBackgroundBlur" BOOLEAN NOT NULL DEFAULT true,
    "websiteDefaultAvatar" TEXT,
    "websiteTos" TEXT,
    "websiteThemeDefault" TEXT NOT NULL DEFAULT 'system',
    "websiteThemeDark" TEXT NOT NULL DEFAULT 'builtin:dark_gray',
    "websiteThemeLight" TEXT NOT NULL DEFAULT 'builtin:light_gray',
    "oauthBypassLocalLogin" BOOLEAN NOT NULL DEFAULT false,
    "oauthLoginOnly" BOOLEAN NOT NULL DEFAULT false,
    "oauthDiscordClientId" TEXT,
    "oauthDiscordClientSecret" TEXT,
    "oauthDiscordRedirectUri" TEXT,
    "oauthDiscordAllowedIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "oauthDiscordDeniedIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "oauthGoogleClientId" TEXT,
    "oauthGoogleClientSecret" TEXT,
    "oauthGoogleRedirectUri" TEXT,
    "oauthGithubClientId" TEXT,
    "oauthGithubClientSecret" TEXT,
    "oauthGithubRedirectUri" TEXT,
    "oauthOidcClientId" TEXT,
    "oauthOidcClientSecret" TEXT,
    "oauthOidcAuthorizeUrl" TEXT,
    "oauthOidcTokenUrl" TEXT,
    "oauthOidcUserinfoUrl" TEXT,
    "oauthOidcRedirectUri" TEXT,
    "mfaTotpEnabled" BOOLEAN NOT NULL DEFAULT false,
    "mfaTotpIssuer" TEXT NOT NULL DEFAULT 'NodeCast',
    "mfaPasskeys" BOOLEAN NOT NULL DEFAULT false,
    "ratelimitEnabled" BOOLEAN NOT NULL DEFAULT true,
    "ratelimitMax" INTEGER NOT NULL DEFAULT 10,
    "ratelimitWindow" INTEGER,
    "ratelimitAdminBypass" BOOLEAN NOT NULL DEFAULT true,
    "ratelimitAllowList" TEXT[],
    "httpWebhookOnUpload" TEXT,
    "httpWebhookOnShorten" TEXT,
    "discordWebhookUrl" TEXT,
    "discordUsername" TEXT,
    "discordAvatarUrl" TEXT,
    "discordOnUploadWebhookUrl" TEXT,
    "discordOnUploadUsername" TEXT,
    "discordOnUploadAvatarUrl" TEXT,
    "discordOnUploadContent" TEXT,
    "discordOnUploadEmbed" JSONB,
    "discordOnShortenWebhookUrl" TEXT,
    "discordOnShortenUsername" TEXT,
    "discordOnShortenAvatarUrl" TEXT,
    "discordOnShortenContent" TEXT,
    "discordOnShortenEmbed" JSONB,
    "pwaEnabled" BOOLEAN NOT NULL DEFAULT false,
    "pwaTitle" TEXT NOT NULL DEFAULT 'NodeCast',
    "pwaShortName" TEXT NOT NULL DEFAULT 'NodeCast',
    "pwaDescription" TEXT NOT NULL DEFAULT 'NodeCast Enterprise File Server',
    "pwaThemeColor" TEXT NOT NULL DEFAULT '#000000',
    "pwaBackgroundColor" TEXT NOT NULL DEFAULT '#000000',
    "domains" TEXT[] DEFAULT ARRAY[]::TEXT[],

    CONSTRAINT "NodeCast_pkey" PRIMARY KEY ("id")
);
